"""empty message

Revision ID: 569096b872fe
Revises: 6d6f7dcc45b4
Create Date: 2024-04-18 00:27:03.446868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569096b872fe'
down_revision = '6d6f7dcc45b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index('ix_comment_post_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index('ix_comment_post_id', ['post_id'], unique=False)
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
