"""empty message

Revision ID: e0d72e92ecb9
Revises: 18a5cf241d96
Create Date: 2024-04-17 18:03:51.111846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d72e92ecb9'
down_revision = '18a5cf241d96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=40), nullable=False))
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_post_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_category'))
        batch_op.alter_column('body',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=140),
               existing_nullable=False)
        batch_op.drop_column('category')

    # ### end Alembic commands ###
