"""empty message

Revision ID: ec70cfbfb53e
Revises: aa164321cfb2
Create Date: 2024-05-12 16:59:40.409510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec70cfbfb53e'
down_revision = 'aa164321cfb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dislike', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_dislike_comment_id'), ['comment_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_dislike_comment_id'), 'comment', ['comment_id'], ['id'])

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_like_comment_id'), ['comment_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_like_comment_id'), 'comment', ['comment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_like_comment_id'))
        batch_op.drop_column('comment_id')

    with op.batch_alter_table('dislike', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_dislike_comment_id'))
        batch_op.drop_column('comment_id')

    # ### end Alembic commands ###
